version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=me
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  user-app:
    build:
      context: ./ 
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:me@postgres:5432
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy